---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content/photoshoots
  label: Photoshoots
  create: all
  match: "**/*"
  templates:
  - project
- type: directory
  path: content/popups
  label: Popups
  create: all
  match: "*"
  templates:
  - project-group
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: 0.45.1
