---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content
  label: Home
  create: all
  match: "*"
  templates:
  - default
- type: directory
  path: content/165_duane_st
  label: 165 Duane St
  create: all
  match: "**/*"
- type: directory
  path: content/projects/170a_suffolk_st_pt2
  label: 170A Suffolk St (Pt.2)
  create: all
  match: "**/*"
- type: directory
  path: content/projects/275a_malcolm_x_blvd
  label: 275A Malcolm X Blvd
  create: all
  match: "**/*"
- type: directory
  path: content/projects/170a_sufflolk_st_pt1
  label: 170A Suffolk St (Pt.1)
  create: all
  match: "**/*"
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: 0.45.1
