---
label: Designer
hide_body: false
is_partial: false
fields:
- type: text
  name: title
  label: Title
  description: Enter page title
  config:
    required: true
- type: text
  name: designer-name
  label: Designer Name
  description: Enter designer name
- type: image_gallery
  name: gallery
  label: Gallery
  description: Add images here
pages:
- content/_index.md
- content/designers/alterita.md
- content/designers/annabell-p-lee.md
- content/designers/alexa-stark.md
- content/designers/anna-pierce.md
