---
label: Default
hide_body: false
is_partial: false
fields:
- type: text
  name: title
  label: Title
  description: Enter page title
  config:
    required: true
pages:
- content/170a_suffolk_st_pt2/india-2.md
- content/info.md
- content/_index.md
