---
label: Default
hide_body: false
is_partial: false
fields:
- type: text
  name: title
  label: Title
  description: Enter page title
  config:
    required: true
- type: image_gallery
  name: gallery
  label: Gallery
  description: Add images here
pages:
- content/_index.md
- content/info.md
