---
label: designer
hide_body: false
is_partial: false
fields:
- type: text
  name: title
  label: Title
  description: Enter page title
  config:
    required: true
- type: text
  name: name
  label: Name
  description: Enter designer name
- type: image_gallery
  name: gallery
  label: Gallery
  description: Add images here
pages:
- content/_index.md
- content/info.md
- content/designers.md
- content/designers/alexa-stark.md
- content/designers/alterita.md
- content/designers/annabell-p-lee.md
