---
label: Default
hide_body: false
is_partial: false
fields:
- type: text
  name: title
  label: Title
  description: Enter page title
  config:
    required: true
pages:
- content/165_duane_st/claire-mckinney.md
- content/info.md
- content/_index.md
