---
label: Designer
hide_body: false
is_partial: false
fields:
- type: text
  name: title
  label: Title
  description: Enter page title
  config:
    required: true
- type: text
  name: designer
  label: Designer
  description: Enter designer name
- type: image_gallery
  name: gallery
  label: Gallery
  description: Add images here
pages:
- content/designers/christie-keshet.md
- content/designers/bror-august.md
- content/designers/brie-moreno.md
- content/designers/carolyn-killcoyne-voyta.md
- content/designers/by-tyler.md
- content/designers/claire-mckinney.md
- content/designers/cm-carney.md
- content/designers/anna-pierce.md
- content/designers/balin.md
- content/_index.md
- content/designers/alterita.md
- content/designers/annabell-p-lee.md
- content/designers/alexa-stark.md
- content/designers/autobody.md
