---
label: Project
hide_body: false
is_partial: false
fields:
- type: text
  label: Title
  name: title
  description: Enter photoshoot title
  config:
    required: true
- type: text
  name: date
  label: Date
  description: Enter photoshoot date
- type: file
  name: thumbnail
  label: Thumbnail
  description: Enter image for thumbnail
  config:
    maxSize: '20'
- type: image_gallery
  name: gallery
  label: Gallery
  description: Enter all images for slideshow
- type: select
  config:
    source:
      type: simple
      section: popups
    options:
    - 170A Suffolk St Pt.2
    - 170A Suffolk St Pt.1
    - 275 A Malcolm X Blvd
    - 165 Duane St
  label: Parent Project
  name: parent_project
  description: Select the parent project for the photoshoot
pages:
- content/projects/165_duane_st/india-salvor-menuez-in-chinatown.md
