---
label: Project
hide_body: false
is_partial: false
fields:
- type: text
  label: Title
  name: title
  description: Enter photoshoot title
  config:
    required: true
- type: text
  name: date
  label: Date
  description: Enter photoshoot date
- type: file
  name: thumbnail
  label: Thumbnail
  description: Enter image for thumbnail
  config:
    maxSize: '20'
- type: image_gallery
  name: gallery
  label: Gallery
  description: Enter all images for slideshow
pages:
- content/170a_suffolk_st_pt2/new-project.md
- content/165_duane_st/claire-mckinney.md
- content/165_duane_st/india-salvor-menuz.md
